Update docker-compose.yml

diff --git a/apps/lobe-chat-data/latest/docker-compose.yml b/apps/lobe-chat-data/latest/docker-compose.yml
--- a/apps/lobe-chat-data/latest/docker-compose.yml
+++ b/apps/lobe-chat-data/latest/docker-compose.yml
@@ -1,4 +1,3 @@
-name: lobe-chat-database
 services:
   network-service:
     image: alpine
@@ -8,7 +7,7 @@ services:
       - '${MINIO_PORT}:${MINIO_PORT}' # MinIO API
       - '9001:9001' # MinIO Console
       - '${CASDOOR_PORT}:${CASDOOR_PORT}' # Casdoor
-      - '${LOBE_PORT}:3210' # LobeChat
+      - '${PANEL_APP_PORT_HTTP}:3210' # LobeChat
     command: tail -f /dev/null
     networks:
       - lobe-network
@@ -43,17 +42,20 @@ services:
     env_file:
       - .env
     restart: always
-    command: >
-      sh -c '
-        mc alias set myminio http://localhost:${MINIO_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
-        mc mb myminio/${MINIO_LOBE_BUCKET} ||
-        true &&
-        minio server /etc/minio/data --address ":${MINIO_PORT}" --console-address ":9001"'
-    healthcheck:
-      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT}/minio/health/live"]
-      interval: 5s
-      timeout: 5s
-      retries: 5
+    entrypoint: >
+      /bin/sh -c "
+        minio server /etc/minio/data --address ':${MINIO_PORT}' --console-address ':9001' &
+        MINIO_PID=\$!
+        while ! curl -s http://localhost:${MINIO_PORT}/minio/health/live; do
+          echo 'Waiting for MinIO to start...'
+          sleep 1
+        done
+        sleep 5
+        mc alias set myminio http://localhost:${MINIO_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
+        echo 'Creating bucket ${MINIO_LOBE_BUCKET}'
+        mc mb myminio/${MINIO_LOBE_BUCKET}
+        wait \$MINIO_PID
+      "
 
   casdoor:
     image: casbin/casdoor
@@ -117,47 +119,46 @@ services:
     env_file:
       - .env
     restart: always
-    command: >
-      sh -c '
-        if [ $(wget --timeout=5 --spider --server-response ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep -c "HTTP/1.1 200 OK") -eq 0 ]; then
-          echo "⚠️Warining: Unable to fetch OIDC configuration from Casdoor"
-          echo "Request URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration"
-          echo "Read more at: https://lobehub.com/docs/self-hosting/server-database/docker-compose#necessary-configuration"
-          echo ""
-          echo "⚠️注意：无法从 Casdoor 获取 OIDC 配置"
-          echo "请求 URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration"
-          echo "了解更多：https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose#necessary-configuration"
-          echo ""
+    entrypoint: >
+      /bin/sh -c "
+        /bin/node /app/startServer.js &
+        LOBE_PID=\$!
+        sleep 3
+        if [ $(wget --timeout=5 --spider --server-response ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep -c 'HTTP/1.1 200 OK') -eq 0 ]; then
+          echo '⚠️Warining: Unable to fetch OIDC configuration from Casdoor'
+          echo 'Request URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration'
+          echo 'Read more at: https://lobehub.com/docs/self-hosting/server-database/docker-compose#necessary-configuration'
+          echo ''
+          echo '⚠️注意：无法从 Casdoor 获取 OIDC 配置'
+          echo '请求 URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration'
+          echo '了解更多：https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose#necessary-configuration'
+          echo ''
         else
-          if ! wget -O - --timeout=5 ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep "issuer" | grep "${AUTH_CASDOOR_ISSUER}"; then
-            printf "❌Error: The Auth issuer is conflict, Issuer in OIDC configuration is: %s" $(wget -O - --timeout=5 ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep -E "issuer.*" | awk -F "\"" "{print \$4}")
-            echo " , but the issuer in .env file is: ${AUTH_CASDOOR_ISSUER} "
-            echo "Request URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration"
-            echo "Read more at: https://lobehub.com/docs/self-hosting/server-database/docker-compose#necessary-configuration"
-            echo ""
-            printf "❌错误：Auth 的 issuer 冲突，OIDC 配置中的 issuer 是：%s" $(wget -O - --timeout=5 ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep -E "issuer.*" | awk -F "\"" "{print \$4}")
-            echo " , 但 .env 文件中的 issuer 是：${AUTH_CASDOOR_ISSUER} "
-            echo "请求 URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration"
-            echo "了解更多：https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose#necessary-configuration"
-            echo ""
+          if ! wget -O - --timeout=5 ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep 'issuer' | grep ${AUTH_CASDOOR_ISSUER}; then
+            printf '❌Error: The Auth issuer is conflict, Issuer in OIDC configuration is: %s' \$(wget -O - --timeout=5 ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep -E 'issuer.*' | awk -F '\"' '{print \$4}')
+            echo ' , but the issuer in .env file is: ${AUTH_CASDOOR_ISSUER} '
+            echo 'Request URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration'
+            echo 'Read more at: https://lobehub.com/docs/self-hosting/server-database/docker-compose#necessary-configuration'
+            echo ''
+            printf '❌错误：Auth 的 issuer 冲突，OIDC 配置中的 issuer 是：%s' \$(wget -O - --timeout=5 ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep -E 'issuer.*' | awk -F '\"' '{print \$4}')
+            echo ' , 但 .env 文件中的 issuer 是：${AUTH_CASDOOR_ISSUER} '
+            echo '请求 URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration'
+            echo '了解更多：https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose#necessary-configuration'
+            echo ''
           fi
         fi
-        if [ $(wget --timeout=5 --spider --server-response ${S3_ENDPOINT}/minio/health/live 2>&1 | grep -c "HTTP/1.1 200 OK") -eq 0 ]; then
-          echo "⚠️Warining: Unable to fetch MinIO health status"
-          echo "Request URL: ${S3_ENDPOINT}/minio/health/live"
-          echo "Read more at: https://lobehub.com/docs/self-hosting/server-database/docker-compose#necessary-configuration"
-          echo ""
-          echo "⚠️注意：无法获取 MinIO 健康状态"
-          echo "请求 URL: ${S3_ENDPOINT}/minio/health/live"
-          echo "了解更多：https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose#necessary-configuration"
-          echo ""
+        if [ $(wget --timeout=5 --spider --server-response ${S3_ENDPOINT}/minio/health/live 2>&1 | grep -c 'HTTP/1.1 200 OK') -eq 0 ]; then
+          echo '⚠️Warining: Unable to fetch MinIO health status'
+          echo 'Request URL: ${S3_ENDPOINT}/minio/health/live'
+          echo 'Read more at: https://lobehub.com/docs/self-hosting/server-database/docker-compose#necessary-configuration'
+          echo ''
+          echo '⚠️注意：无法获取 MinIO 健康状态'
+          echo '请求 URL: ${S3_ENDPOINT}/minio/health/live'
+          echo '了解更多：https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose#necessary-configuration'
+          echo ''
         fi
-        exec /bin/node /app/startServer.js'
-    healthcheck:
-      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3210"]
-      interval: 5s
-      timeout: 5s
-      retries: 5
+        wait \$LOBE_PID
+      "
 
 volumes:
   data:
